export const siteConfig = {
  name: "Panashe Tech Solutions",
  tagline: "Transforming Business Through Technology",
  description: "Premium technology solutions for forward-thinking businesses in Zimbabwe and beyond.",
  founder: "Panashe Party",
  founderTitle: "Founder & Managing Director",
  founderBio: "A passionate technology entrepreneur helping businesses grow through innovative digital solutions.",
  address: "Harare, Zimbabwe",
  phone: "+263 77 690 2542",
  whatsapp: "+263776902542",
  email: "hello@panashetechsolution.co.zw",
  website: "panashetechsolution.co.zw",
  hours: "Mon – Fri: 8:00 AM – 6:00 PM | Sat: 9:00 AM – 2:00 PM",
  social: {
    linkedin: "https://linkedin.com/company/panashe-tech-solutions",
    twitter: "https://twitter.com/PanasheTech",
    facebook: "https://facebook.com/PanasheTechSolutions",
    instagram: "https://instagram.com/panashetechsolutions",
    github: "https://github.com/panashetech",
  },
};

export const navLinks = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Services", href: "/services" },
  { label: "Portfolio", href: "/portfolio" },
  { label: "Pricing", href: "/pricing" },
  { label: "Blog", href: "/blog" },
  { label: "Contact", href: "/contact" },
];

export const services = [
  {
    id: "web-development",
    icon: "Globe",
    title: "Website Development",
    shortDesc: "Professional, high-converting websites that represent your brand perfectly.",
    description: "We build stunning, fast, SEO-optimized websites that convert visitors into customers. From corporate sites to e-commerce platforms, we deliver results.",
    features: ["Corporate Websites", "E-Commerce Stores", "Landing Pages", "Website Redesigns", "CMS Integration", "SEO Optimization"],
    color: "from-blue-600 to-cyan-500",
    href: "/services#web-development",
  },
  {
    id: "software-development",
    icon: "Code2",
    title: "Custom Software",
    shortDesc: "Tailor-made software solutions built for your exact business needs.",
    description: "Custom business applications, SaaS platforms, and enterprise software built with modern technologies that scale with your business.",
    features: ["Business Management Systems", "SaaS Platforms", "ERP Solutions", "API Development", "Database Design", "System Integration"],
    color: "from-violet-600 to-blue-500",
    href: "/services#software-development",
  },
  {
    id: "mobile-apps",
    icon: "Smartphone",
    title: "Mobile Applications",
    shortDesc: "Native and cross-platform apps for Android and iOS.",
    description: "We develop powerful, intuitive mobile applications that your customers will love. From concept to App Store — we handle everything.",
    features: ["Android Apps", "iOS Apps", "Cross-Platform (React Native)", "App Store Deployment", "UI/UX Design", "Maintenance & Updates"],
    color: "from-cyan-500 to-teal-500",
    href: "/services#mobile-apps",
  },
  {
    id: "cybersecurity",
    icon: "Shield",
    title: "Cybersecurity",
    shortDesc: "Protect your business from cyber threats with enterprise-grade security.",
    description: "Comprehensive cybersecurity solutions including vulnerability assessments, penetration testing, and security consulting to safeguard your digital assets.",
    features: ["Security Assessments", "Penetration Testing", "Security Audits", "Threat Monitoring", "Employee Training", "Compliance Consulting"],
    color: "from-red-500 to-orange-500",
    href: "/services#cybersecurity",
  },
  {
    id: "cloud-services",
    icon: "Cloud",
    title: "Cloud Services",
    shortDesc: "Scale your infrastructure with reliable cloud solutions.",
    description: "Cloud migration, hosting, and infrastructure management services on AWS and Azure. We make the cloud work for your business.",
    features: ["Cloud Migration", "AWS & Azure Setup", "Hosting Solutions", "Server Management", "Backup & Recovery", "Performance Optimization"],
    color: "from-sky-500 to-blue-600",
    href: "/services#cloud-services",
  },
  {
    id: "it-consulting",
    icon: "Lightbulb",
    title: "IT Consulting",
    shortDesc: "Expert technology guidance to align IT with your business goals.",
    description: "Strategic IT consulting to help businesses make informed technology decisions, reduce costs, and improve efficiency.",
    features: ["Technology Strategy", "Digital Transformation", "IT Roadmapping", "Vendor Selection", "Process Optimization", "Training & Support"],
    color: "from-amber-500 to-yellow-500",
    href: "/services#it-consulting",
  },
  {
    id: "ai-solutions",
    icon: "Brain",
    title: "AI & Automation",
    shortDesc: "Harness the power of AI to automate and accelerate your business.",
    description: "We integrate cutting-edge AI solutions including chatbots, automation workflows, and machine learning to give your business a competitive edge.",
    features: ["AI Chatbots", "Business Automation", "Machine Learning", "Data Analytics", "AI Integration", "Process Automation"],
    color: "from-purple-600 to-pink-500",
    href: "/services#ai-solutions",
  },
  {
    id: "tech-support",
    icon: "Headphones",
    title: "Technical Support",
    shortDesc: "Reliable 24/7 technical support to keep your systems running.",
    description: "Dedicated technical support and maintenance services ensuring your systems are always running at peak performance.",
    features: ["24/7 Support", "Remote Assistance", "On-Site Support", "System Maintenance", "Performance Monitoring", "Issue Resolution"],
    color: "from-green-500 to-emerald-500",
    href: "/services#tech-support",
  },
];

export const stats = [
  { value: 50, suffix: "+", label: "Projects Completed" },
  { value: 30, suffix: "+", label: "Happy Clients" },
  { value: 24, suffix: "/7", label: "Support Available" },
  { value: 15, suffix: "+", label: "Technologies Used" },
];

export const portfolio = [
  {
    id: "1",
    title: "RetailPro Zimbabwe",
    category: "E-Commerce",
    description: "Full-stack e-commerce platform with inventory management, payment integration, and analytics dashboard for a leading retail chain.",
    tech: ["Next.js", "Node.js", "PostgreSQL", "Stripe"],
    result: "3x increase in online sales within 3 months",
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80",
    color: "from-blue-600 to-cyan-500",
  },
  {
    id: "2",
    title: "EduConnect Platform",
    category: "EdTech",
    description: "Online learning management system for a network of private schools, featuring live classes, assessments, and parent portals.",
    tech: ["React", "TypeScript", "Firebase", "WebRTC"],
    result: "5,000+ students enrolled in first semester",
    image: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800&q=80",
    color: "from-violet-600 to-blue-500",
  },
  {
    id: "3",
    title: "HealthTrack Mobile App",
    category: "Healthcare",
    description: "Cross-platform mobile app for a private hospital enabling appointment booking, medical records access, and telemedicine.",
    tech: ["React Native", "Node.js", "MongoDB", "AWS"],
    result: "4.8★ app rating, 2,000+ downloads",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80",
    color: "from-green-500 to-teal-500",
  },
  {
    id: "4",
    title: "FinanceHub Dashboard",
    category: "FinTech",
    description: "Real-time financial analytics dashboard with automated reporting for a microfinance institution serving 10,000+ clients.",
    tech: ["Next.js", "Python", "PostgreSQL", "Chart.js"],
    result: "80% reduction in manual reporting time",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "5",
    title: "PropertyView Platform",
    category: "Real Estate",
    description: "Property listing and management platform with virtual tours, lead management, and automated email marketing.",
    tech: ["Next.js", "Prisma", "PostgreSQL", "AWS S3"],
    result: "200% increase in qualified leads",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80",
    color: "from-sky-500 to-blue-600",
  },
  {
    id: "6",
    title: "LogiTrack System",
    category: "Logistics",
    description: "Real-time fleet tracking and logistics management system with driver app, client portal, and automated dispatch.",
    tech: ["React", "Node.js", "Google Maps API", "Socket.io"],
    result: "40% improvement in delivery efficiency",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80",
    color: "from-red-500 to-pink-500",
  },
];

export const testimonials = [
  {
    id: "1",
    name: "Tinashe Mhuka",
    role: "CEO, RetailPro Zimbabwe",
    content: "Panashe Tech Solutions transformed our entire online presence. The e-commerce platform they built tripled our online revenue in just 3 months. The team is professional, responsive, and truly understands business needs.",
    rating: 5,
    avatar: "TM",
  },
  {
    id: "2",
    name: "Dr. Rutendo Chieza",
    role: "Director, HealthTrack",
    content: "Working with Panashe Party directly was a game-changer. He understood our complex healthcare requirements and delivered a mobile app that our patients absolutely love. Outstanding quality and support.",
    rating: 5,
    avatar: "RC",
  },
  {
    id: "3",
    name: "Samuel Banda",
    role: "IT Manager, FinanceHub",
    content: "The financial dashboard they built saved our team hundreds of hours per month. The code quality is excellent and the ongoing support has been exceptional. I highly recommend Panashe Tech Solutions.",
    rating: 5,
    avatar: "SB",
  },
  {
    id: "4",
    name: "Grace Mutasa",
    role: "Founder, EduConnect",
    content: "From concept to launch in 8 weeks — I was blown away by the speed and quality. The LMS platform handles thousands of students seamlessly. Panashe Tech Solutions is our go-to technology partner.",
    rating: 5,
    avatar: "GM",
  },
  {
    id: "5",
    name: "James Ncube",
    role: "Operations Director, LogiTrack",
    content: "The fleet management system has completely revolutionized our operations. Real-time tracking, automated dispatch, driver apps — everything works perfectly. Best technology investment we've made.",
    rating: 5,
    avatar: "JN",
  },
];

export const pricingPlans = [
  {
    id: "starter",
    name: "Starter",
    price: 299,
    period: "once-off",
    description: "Perfect for small businesses and startups needing a professional online presence.",
    features: [
      "5-page professional website",
      "Mobile responsive design",
      "Contact form integration",
      "Basic SEO optimization",
      "Google Analytics setup",
      "1 month free support",
      "Social media links",
      "WhatsApp button",
    ],
    notIncluded: ["E-commerce functionality", "Custom web app", "CMS dashboard"],
    cta: "Get Started",
    color: "from-blue-500 to-cyan-500",
    popular: false,
  },
  {
    id: "business",
    name: "Business",
    price: 799,
    period: "once-off",
    description: "For growing businesses that need advanced features and a powerful web presence.",
    features: [
      "Up to 15-page website",
      "CMS dashboard (edit content yourself)",
      "E-commerce (up to 100 products)",
      "Advanced SEO optimization",
      "Blog functionality",
      "Email marketing integration",
      "3 months free support",
      "Performance optimization",
      "SSL certificate setup",
      "Custom domain setup",
    ],
    notIncluded: ["Custom web application", "Mobile app"],
    cta: "Most Popular",
    color: "from-electric to-cyan",
    popular: true,
  },
  {
    id: "professional",
    name: "Professional",
    price: 1999,
    period: "once-off",
    description: "Advanced solutions for established businesses needing custom applications.",
    features: [
      "Everything in Business",
      "Custom web application",
      "User authentication system",
      "Admin dashboard",
      "Database design & setup",
      "API development",
      "Payment gateway integration",
      "6 months free support",
      "Performance monitoring",
      "Security hardening",
      "Staff training",
    ],
    notIncluded: ["Mobile app development"],
    cta: "Get Started",
    color: "from-violet-600 to-blue-500",
    popular: false,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 0,
    period: "custom",
    description: "Fully custom solutions for large organizations with complex requirements.",
    features: [
      "Everything in Professional",
      "Mobile app (Android + iOS)",
      "Cloud infrastructure setup",
      "AI & automation integration",
      "Cybersecurity assessment",
      "Dedicated project manager",
      "12 months priority support",
      "SLA agreement",
      "Team training",
      "Unlimited revisions",
      "Source code ownership",
    ],
    notIncluded: [],
    cta: "Contact Us",
    color: "from-navy to-electric",
    popular: false,
  },
];

export const blogPosts = [
  {
    id: "1",
    title: "Why Every Zimbabwe Business Needs a Professional Website in 2025",
    excerpt: "With over 6 million internet users in Zimbabwe, not having a website means missing out on a massive opportunity to grow your business.",
    category: "Business Technology",
    date: "2025-01-10",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    slug: "why-zimbabwe-business-needs-website-2025",
  },
  {
    id: "2",
    title: "Top 5 Cybersecurity Threats Facing African Businesses in 2025",
    excerpt: "Cybercrime costs African businesses billions annually. Here are the top threats and how to protect your organization.",
    category: "Cybersecurity",
    date: "2025-01-18",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80",
    slug: "cybersecurity-threats-african-businesses-2025",
  },
  {
    id: "3",
    title: "How AI is Transforming Small Businesses in Zimbabwe",
    excerpt: "Artificial Intelligence is no longer just for large corporations. Discover how small businesses in Zimbabwe are using AI to compete.",
    category: "AI & Technology",
    date: "2025-01-25",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80",
    slug: "ai-transforming-small-businesses-zimbabwe",
  },
  {
    id: "4",
    title: "Cloud vs On-Premise: What's Right for Your Zimbabwe Business?",
    excerpt: "Deciding between cloud and on-premise infrastructure? We break down the costs, benefits, and considerations for Zimbabwe businesses.",
    category: "Cloud Services",
    date: "2025-02-02",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&q=80",
    slug: "cloud-vs-on-premise-zimbabwe-business",
  },
  {
    id: "5",
    title: "Building a Mobile App: What You Need to Know Before You Start",
    excerpt: "Thinking about building a mobile app for your business? Here's everything you need to know about the process, costs, and timeline.",
    category: "Mobile Development",
    date: "2025-02-10",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80",
    slug: "building-mobile-app-what-you-need-to-know",
  },
  {
    id: "6",
    title: "10 Signs Your Business Website Needs a Redesign",
    excerpt: "Is your website costing you customers? Look out for these 10 warning signs that it's time for a professional website redesign.",
    category: "Web Development",
    date: "2025-02-18",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80",
    slug: "10-signs-business-website-needs-redesign",
  },
];

export const faqs = [
  { q: "How long does it take to build a website?", a: "A standard business website takes 1–2 weeks. Custom web applications take 4–12 weeks depending on complexity. We always provide a detailed timeline before starting." },
  { q: "What is included in your website packages?", a: "All packages include design, development, mobile responsiveness, basic SEO, contact forms, and deployment. Higher packages include CMS, e-commerce, and more. See our Pricing page for details." },
  { q: "Do I own my website after it's built?", a: "Yes, 100%. You own all code, design files, content, and domains. We hand over everything upon project completion." },
  { q: "What are your payment terms?", a: "We typically require 50% upfront and 50% upon completion. For larger projects, we can arrange milestone-based payments." },
  { q: "Can you work with clients outside Zimbabwe?", a: "Absolutely. We work with clients across Africa and internationally. We use Zoom, Teams, and WhatsApp for communication and accept international payments." },
  { q: "Do you provide ongoing support after launch?", a: "Yes. All packages include free support periods. We also offer monthly maintenance retainers for ongoing updates, security patches, and technical support." },
  { q: "What technologies do you use?", a: "We use modern, industry-standard technologies: Next.js, React, TypeScript, Node.js, Python, PostgreSQL, MongoDB, AWS, Azure, Docker, and more." },
  { q: "Can you redesign my existing website?", a: "Yes. We specialize in website redesigns that improve performance, aesthetics, and conversion rates while preserving your SEO rankings." },
  { q: "Do you build e-commerce websites?", a: "Yes. We build custom e-commerce solutions with payment gateway integration (Paynow, Stripe, PayPal), inventory management, and analytics." },
  { q: "How do you handle project communication?", a: "You communicate directly with Panashe Party (Founder) via WhatsApp, email, or Zoom. No middlemen — direct, clear communication throughout." },
  { q: "Do you offer cybersecurity services for small businesses?", a: "Yes. We offer affordable cybersecurity assessments and security hardening tailored for small and medium businesses in Zimbabwe." },
  { q: "Can you integrate AI into my existing business systems?", a: "Yes. We can integrate AI chatbots, automation workflows, and data analytics into your existing systems to improve efficiency." },
  { q: "What is your refund policy?", a: "We have a satisfaction guarantee. If you are not happy with our work at any milestone, we will revise until you are satisfied or refund the relevant portion." },
  { q: "Do you help with domain and hosting?", a: "Yes. We handle domain registration, hosting setup, SSL certificates, and all technical configuration as part of our service." },
  { q: "How do I get started?", a: "Simply send us a WhatsApp message or fill out our contact form. We'll schedule a free 30-minute consultation to discuss your project and provide a no-obligation quote." },
];

export const industries = [
  { name: "Retail & E-Commerce", icon: "ShoppingBag", desc: "Digital stores, inventory systems, POS integration" },
  { name: "Education", icon: "GraduationCap", desc: "LMS platforms, student portals, e-learning tools" },
  { name: "Healthcare", icon: "Heart", desc: "Patient management, telemedicine, health apps" },
  { name: "Hospitality", icon: "Hotel", desc: "Booking systems, hotel management, restaurant apps" },
  { name: "Finance & FinTech", icon: "TrendingUp", desc: "Dashboards, payment systems, financial tools" },
  { name: "Real Estate", icon: "Building", desc: "Property listings, CRM systems, virtual tours" },
  { name: "Startups", icon: "Rocket", desc: "MVPs, pitch decks, rapid prototyping" },
  { name: "NGOs & Non-Profits", icon: "Globe", desc: "Donation platforms, impact reporting, CMS" },
];

export const techStack = [
  { name: "React", category: "Frontend" },
  { name: "Next.js", category: "Frontend" },
  { name: "TypeScript", category: "Frontend" },
  { name: "Tailwind CSS", category: "Frontend" },
  { name: "Node.js", category: "Backend" },
  { name: "Python", category: "Backend" },
  { name: "PostgreSQL", category: "Database" },
  { name: "MongoDB", category: "Database" },
  { name: "AWS", category: "Cloud" },
  { name: "Azure", category: "Cloud" },
  { name: "Docker", category: "DevOps" },
  { name: "GitHub", category: "DevOps" },
  { name: "React Native", category: "Mobile" },
  { name: "Firebase", category: "Backend" },
  { name: "Prisma", category: "Database" },
];

export const process = [
  { step: "01", title: "Discovery", desc: "We start with a deep-dive consultation to understand your business, goals, and requirements.", icon: "Search" },
  { step: "02", title: "Planning", desc: "We create a detailed project plan, wireframes, and technical architecture tailored to your needs.", icon: "FileText" },
  { step: "03", title: "Development", desc: "Our team builds your solution using modern technologies with regular progress updates.", icon: "Code2" },
  { step: "04", title: "Launch", desc: "Rigorous testing, optimization, and deployment to ensure a flawless go-live experience.", icon: "Rocket" },
  { step: "05", title: "Support", desc: "Ongoing maintenance, updates, and dedicated support to keep your systems performing perfectly.", icon: "Headphones" },
];
