import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#07070D',
        surface:    '#0D0D1A',
        surface2:   '#111122',
        border:     '#1A1A30',
        border2:    '#252545',
        gold:  { DEFAULT: '#C9A84C', light: '#E2C97A', dim: '#7A6530' },
        white: '#F0EDE8',
        muted: '#6A7890',
        green: '#00FF88',
        navy:  { DEFAULT: '#07070D', light: '#0D0D1A', dark: '#030308' },
        electric: { DEFAULT: '#C9A84C', light: '#E2C97A', dark: '#7A6530' },
        cyan: { DEFAULT: '#E2C97A', light: '#F0DFA0', dark: '#C9A84C' },
        violet: { DEFAULT: '#252545', light: '#303060', dark: '#1A1A30' },
        input:      'hsl(var(--input))',
        ring:       'hsl(var(--ring))',
        foreground: 'hsl(var(--foreground))',
        primary:     { DEFAULT: 'hsl(var(--primary))',     foreground: 'hsl(var(--primary-foreground))' },
        secondary:   { DEFAULT: 'hsl(var(--secondary))',   foreground: 'hsl(var(--secondary-foreground))' },
        accent:      { DEFAULT: 'hsl(var(--accent))',      foreground: 'hsl(var(--accent-foreground))' },
        card:        { DEFAULT: 'hsl(var(--card))',        foreground: 'hsl(var(--card-foreground))' },
        popover:     { DEFAULT: 'hsl(var(--popover))',     foreground: 'hsl(var(--popover-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
      },
      fontFamily: {
        sans:     ['var(--font-outfit)', 'Outfit', 'sans-serif'],
        display:  ['var(--font-outfit)', 'Outfit', 'sans-serif'],
        mono:     ['var(--font-ibm-plex-mono)', 'IBM Plex Mono', 'monospace'],
        playfair: ['var(--font-playfair)', 'Playfair Display', 'Georgia', 'serif'],
        jost:     ['var(--font-jost)', 'Jost', 'system-ui', 'sans-serif'],
      },
      backgroundImage: {
        'hero-gradient':  'linear-gradient(160deg, #07070D 0%, #0D0D1A 60%, #111122 100%)',
        'gold-gradient':  'linear-gradient(135deg, #C9A84C 0%, #E2C97A 100%)',
        'card-gradient':  'linear-gradient(135deg, rgba(201,168,76,0.05) 0%, rgba(201,168,76,0.01) 100%)',
        'glass-gradient': 'linear-gradient(135deg, rgba(255,255,255,0.04) 0%, rgba(255,255,255,0.01) 100%)',
        'mesh-gradient':  'radial-gradient(at 20% 20%, rgba(201,168,76,0.07) 0, transparent 50%), radial-gradient(at 80% 80%, rgba(201,168,76,0.04) 0, transparent 50%)',
      },
      animation: {
        'float':          'float 6s ease-in-out infinite',
        'float-delayed':  'float-delayed 8s ease-in-out infinite',
        'pulse-ring':     'pulse-ring 2.5s ease-out infinite',
        'shimmer':        'shimmer 3s ease-in-out infinite',
        'glow-pulse':     'glow-pulse 3s ease-in-out infinite',
        'gradient-shift': 'gradient-shift 8s ease infinite',
        'ticker':         'ticker 30s linear infinite',
        'scan-line':      'scan-line 4s linear infinite',
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up':   'accordion-up 0.2s ease-out',
        'spin-slow':      'spin 25s linear infinite',
      },
      keyframes: {
        float:            { '0%,100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-12px)' } },
        'float-delayed':  { '0%,100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-16px)' } },
        'pulse-ring':     { '0%': { transform: 'scale(0.95)', opacity: '1' }, '70%,100%': { transform: 'scale(1.3)', opacity: '0' } },
        shimmer:          { '0%': { backgroundPosition: '-200% center' }, '100%': { backgroundPosition: '200% center' } },
        'glow-pulse':     { '0%,100%': { opacity: '0.4' }, '50%': { opacity: '0.9' } },
        'gradient-shift': { '0%,100%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' } },
        ticker:           { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-50%)' } },
        'scan-line':      { '0%': { top: '-4px' }, '100%': { top: '100%' } },
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up':   { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
      },
      borderRadius: { lg: 'var(--radius)', md: 'calc(var(--radius) - 2px)', sm: 'calc(var(--radius) - 4px)' },
      boxShadow: {
        'gold-glow':    '0 0 40px rgba(201,168,76,0.25), 0 0 80px rgba(201,168,76,0.08)',
        'gold-glow-sm': '0 0 20px rgba(201,168,76,0.18)',
        'card-premium': '0 4px 6px -1px rgba(0,0,0,0.6), 0 2px 4px -2px rgba(0,0,0,0.4), inset 0 1px 0 rgba(255,255,255,0.04)',
        'glow-blue':    '0 0 40px rgba(201,168,76,0.25)',
        'glow-cyan':    '0 0 40px rgba(226,201,122,0.25)',
        'blue-glow':    '0 0 40px rgba(201,168,76,0.25)',
        'blue-glow-sm': '0 0 20px rgba(201,168,76,0.18)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
export default config;
