import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        navy: { DEFAULT: "#050810", light: "#080D1A", dark: "#020408" },
        electric: { DEFAULT: "#4A90FF", light: "#6BA8FF", dark: "#2563EB" },
        cyan: { DEFAULT: "#00D4FF", light: "#33DDFF", dark: "#00AACC" },
        violet: { DEFAULT: "#7C3AED", light: "#8B5CF6", dark: "#6D28D9" },
        gold: { DEFAULT: "#F59E0B", light: "#FCD34D", dark: "#D97706" },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        display: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
      backgroundImage: {
        "brand-gradient": "linear-gradient(135deg, #050810 0%, #4A90FF 100%)",
        "electric-gradient": "linear-gradient(135deg, #4A90FF 0%, #00D4FF 100%)",
        "violet-gradient": "linear-gradient(135deg, #7C3AED 0%, #4A90FF 100%)",
        "hero-gradient": "linear-gradient(135deg, #050810 0%, #080D1A 60%, #0D1628 100%)",
        "card-gradient": "linear-gradient(135deg, rgba(74,144,255,0.06) 0%, rgba(0,212,255,0.03) 100%)",
        "glass-gradient": "linear-gradient(135deg, rgba(255,255,255,0.06) 0%, rgba(255,255,255,0.02) 100%)",
        "mesh-gradient": "radial-gradient(at 20% 20%, rgba(74,144,255,0.15) 0, transparent 50%), radial-gradient(at 80% 10%, rgba(124,58,237,0.12) 0, transparent 50%), radial-gradient(at 10% 80%, rgba(0,212,255,0.10) 0, transparent 50%), radial-gradient(at 90% 80%, rgba(74,144,255,0.08) 0, transparent 50%)",
        "noise-gradient": "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.04'/%3E%3C/svg%3E\")",
      },
      animation: {
        "float": "float 6s ease-in-out infinite",
        "float-delayed": "float-delayed 8s ease-in-out infinite",
        "pulse-ring": "pulse-ring 2.5s ease-out infinite",
        "shimmer": "shimmer 3s ease-in-out infinite",
        "orbit": "orbit 12s linear infinite",
        "scan-line": "scan-line 4s linear infinite",
        "glow-pulse": "glow-pulse 3s ease-in-out infinite",
        "gradient-shift": "gradient-shift 8s ease infinite",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "spin-slow": "spin 25s linear infinite",
      },
      keyframes: {
        float: { "0%,100%": { transform: "translateY(0px) rotate(0deg)" }, "33%": { transform: "translateY(-12px) rotate(1deg)" }, "66%": { transform: "translateY(-6px) rotate(-1deg)" } },
        "float-delayed": { "0%,100%": { transform: "translateY(0px)" }, "50%": { transform: "translateY(-16px)" } },
        "pulse-ring": { "0%": { transform: "scale(0.95)", opacity: "1" }, "70%,100%": { transform: "scale(1.3)", opacity: "0" } },
        shimmer: { "0%": { backgroundPosition: "-200% center" }, "100%": { backgroundPosition: "200% center" } },
        orbit: { from: { transform: "rotate(0deg) translateX(120px) rotate(0deg)" }, to: { transform: "rotate(360deg) translateX(120px) rotate(-360deg)" } },
        "scan-line": { "0%": { top: "-4px" }, "100%": { top: "100%" } },
        "glow-pulse": { "0%,100%": { opacity: "0.4" }, "50%": { opacity: "0.9" } },
        "gradient-shift": { "0%,100%": { backgroundPosition: "0% 50%" }, "50%": { backgroundPosition: "100% 50%" } },
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
      },
      borderRadius: { lg: "var(--radius)", md: "calc(var(--radius) - 2px)", sm: "calc(var(--radius) - 4px)" },
      boxShadow: {
        "glow-blue": "0 0 40px rgba(74,144,255,0.3), 0 0 80px rgba(74,144,255,0.1)",
        "glow-cyan": "0 0 40px rgba(0,212,255,0.3)",
        "glow-violet": "0 0 40px rgba(124,58,237,0.3)",
        "card-premium": "0 4px 6px -1px rgba(0,0,0,0.5), 0 2px 4px -2px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.05)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
